language: cpp
compiler: gcc
sudo: require
dist: xenial

install:
  - sudo apt-get -y install g++ inkscape libgegl-dev libcairo2-dev libcairo2-dev libcups2-dev libfontconfig-dev libfreetype6-dev libftgl-dev libglu1-mesa-dev libgraphicsmagick++1-dev libimlib2-dev libpng12-dev libreadline-dev libssl-dev libx11-dev libxext-dev libxft-dev libxi-dev libxrandr-dev mesa-common-dev pkg-config xutils-dev zlib1g-dev
  - sudo unlink /usr/bin/gcc && sudo ln -s /usr/bin/gcc-5 /usr/bin/gcc # Needed for std=c++11?
  - sudo unlink /usr/bin/g++ && sudo ln -s /usr/bin/g++-5 /usr/bin/g++ # Needed for std=c++11?

script:
  - export CXXFLAGS='-std=c++11'
  # Harfbuzz
  - wget https://github.com/behdad/harfbuzz/releases/download/2.2.0/harfbuzz-2.2.0.tar.bz2
  - tar xf harfbuzz-2.2.0.tar.bz2
  - cd harfbuzz-2.2.0
  - ./configure --prefix=/usr --disable-dependency-tracking --disable-static --with-glib=no --with-gobject=no --with-cairo=no --with-fontconfig=no --with-icu=no --with-directwrite=no --with-freetype=yes
  - make -j$(nproc)
  - sudo make install
  - pkg-config --cflags harfbuzz
  - cd ..
  # laxkit
  - git clone http://github.com/Laidout/laxkit.git laxkit
  - cd laxkit
  - ./configure --disable-sqlite --relocatable
  - make -j$(nproc)
  - cd ..
  # Laidout 
  - mkdir -p appdir
  - cp AppImage/AppRun appdir/ ; chmod +x appdir/AppRun
  - ./configure --prefix=`pwd`/appdir/usr --relocatable --laxkit=`pwd`/laxkit/lax --nogl --disable-sqlite --force --gegl-version=gegl-0.3
  - make -j$(nproc)
  # TODO: Making the icons requires Inkscape(!); FIXME, see https://github.com/Laidout/laidout
  - git clone https://github.com/Laidout/laidout-icons
  - cp laidout-icons/target-24/* src/icons
  - make install
  - mkdir -p appdir/usr/lib/x86_64-linux-gnu/ ; cp -r /usr/lib/x86_64-linux-gnu/gegl-* appdir/usr/lib/x86_64-linux-gnu/
  - mkdir -p appdir/usr/share/applications/ ; cp deb/laidout.desktop appdir/usr/share/applications/ # FIXME: make install should do this
  - mkdir -p appdir/usr/share/icons/hicolor/scalable/apps/ ; cp src/icons/laidout.svg appdir/usr/share/icons/hicolor/scalable/apps/ # FIXME: make install should do this
  - find appdir/
  - wget -c -nv "https://github.com/probonopd/linuxdeployqt/releases/download/continuous/linuxdeployqt-continuous-x86_64.AppImage"
  - chmod a+x linuxdeployqt-continuous-x86_64.AppImage
  - | 
    ./linuxdeployqt-continuous-x86_64.AppImage appdir/usr/share/applications/*.desktop -appimage \
    -executable=$(readlink -f appdir/usr/share/laidout/*/plugins/geglnodes.so) \
    -executable=appdir/usr/lib/x86_64-linux-gnu/gegl-0.3/hard-light.so \
    -executable=appdir/usr/lib/x86_64-linux-gnu/gegl-0.3/stretch-contrast.so \
    -executable=appdir/usr/lib/x86_64-linux-gnu/gegl-0.3/matting-global.so \
    -executable=appdir/usr/lib/x86_64-linux-gnu/gegl-0.3/plasma.so \
    -executable=appdir/usr/lib/x86_64-linux-gnu/gegl-0.3/convert-format.so \
    -executable=appdir/usr/lib/x86_64-linux-gnu/gegl-0.3/png-save.so \
    -executable=appdir/usr/lib/x86_64-linux-gnu/gegl-0.3/posterize.so \
    -executable=appdir/usr/lib/x86_64-linux-gnu/gegl-0.3/open-buffer.so \
    -executable=appdir/usr/lib/x86_64-linux-gnu/gegl-0.3/noise-simplex.so \
    -executable=appdir/usr/lib/x86_64-linux-gnu/gegl-0.3/color-enhance.so \
    -executable=appdir/usr/lib/x86_64-linux-gnu/gegl-0.3/exr-load.so \
    -executable=appdir/usr/lib/x86_64-linux-gnu/gegl-0.3/diffraction-patterns.so \
    -executable=appdir/usr/lib/x86_64-linux-gnu/gegl-0.3/add.so \
    -executable=appdir/usr/lib/x86_64-linux-gnu/gegl-0.3/tile-seamless.so \
    -executable=appdir/usr/lib/x86_64-linux-gnu/gegl-0.3/grid.so \
    -executable=appdir/usr/lib/x86_64-linux-gnu/gegl-0.3/vector-stroke.so \
    -executable=appdir/usr/lib/x86_64-linux-gnu/gegl-0.3/unsharp-mask.so \
    -executable=appdir/usr/lib/x86_64-linux-gnu/gegl-0.3/emboss.so \
    -executable=appdir/usr/lib/x86_64-linux-gnu/gegl-0.3/plus.so \
    -executable=appdir/usr/lib/x86_64-linux-gnu/gegl-0.3/video-degradation.so \
    -executable=appdir/usr/lib/x86_64-linux-gnu/gegl-0.3/display.so \
    -executable=appdir/usr/lib/x86_64-linux-gnu/gegl-0.3/map-absolute.so \
    -executable=appdir/usr/lib/x86_64-linux-gnu/gegl-0.3/maze.so \
    -executable=appdir/usr/lib/x86_64-linux-gnu/gegl-0.3/channel-mixer.so \
    -executable=appdir/usr/lib/x86_64-linux-gnu/gegl-0.3/sinus.so \
    -executable=appdir/usr/lib/x86_64-linux-gnu/gegl-0.3/distance-transform.so \
    -executable=appdir/usr/lib/x86_64-linux-gnu/gegl-0.3/dst-over.so \
    -executable=appdir/usr/lib/x86_64-linux-gnu/gegl-0.3/color-exchange.so \
    -executable=appdir/usr/lib/x86_64-linux-gnu/gegl-0.3/ppm-load.so \
    -executable=appdir/usr/lib/x86_64-linux-gnu/gegl-0.3/rgbe-save.so \
    -executable=appdir/usr/lib/x86_64-linux-gnu/gegl-0.3/npd.so \
    -executable=appdir/usr/lib/x86_64-linux-gnu/gegl-0.3/buffer-sink.so \
    -executable=appdir/usr/lib/x86_64-linux-gnu/gegl-0.3/lighten.so \
    -executable=appdir/usr/lib/x86_64-linux-gnu/gegl-0.3/gamma.so \
    -executable=appdir/usr/lib/x86_64-linux-gnu/gegl-0.3/warp.so \
    -executable=appdir/usr/lib/x86_64-linux-gnu/gegl-0.3/raw-load.so \
    -executable=appdir/usr/lib/x86_64-linux-gnu/gegl-0.3/map-relative.so \
    -executable=appdir/usr/lib/x86_64-linux-gnu/gegl-0.3/checkerboard.so \
    -executable=appdir/usr/lib/x86_64-linux-gnu/gegl-0.3/texturize-canvas.so \
    -executable=appdir/usr/lib/x86_64-linux-gnu/gegl-0.3/load.so \
    -executable=appdir/usr/lib/x86_64-linux-gnu/gegl-0.3/exr-save.so \
    -executable=appdir/usr/lib/x86_64-linux-gnu/gegl-0.3/convolution-matrix.so \
    -executable=appdir/usr/lib/x86_64-linux-gnu/gegl-0.3/cast-format.so \
    -executable=appdir/usr/lib/x86_64-linux-gnu/gegl-0.3/threshold.so \
    -executable=appdir/usr/lib/x86_64-linux-gnu/gegl-0.3/rgbe-load.so \
    -executable=appdir/usr/lib/x86_64-linux-gnu/gegl-0.3/soft-light.so \
    -executable=appdir/usr/lib/x86_64-linux-gnu/gegl-0.3/text.so \
    -executable=appdir/usr/lib/x86_64-linux-gnu/gegl-0.3/svg-huerotate.so \
    -executable=appdir/usr/lib/x86_64-linux-gnu/gegl-0.3/multiply.so \
    -executable=appdir/usr/lib/x86_64-linux-gnu/gegl-0.3/vignette.so \
    -executable=appdir/usr/lib/x86_64-linux-gnu/gegl-0.3/color-reduction.so \
    -executable=appdir/usr/lib/x86_64-linux-gnu/gegl-0.3/mblur.so \
    -executable=appdir/usr/lib/x86_64-linux-gnu/gegl-0.3/buffer-source.so \
    -executable=appdir/usr/lib/x86_64-linux-gnu/gegl-0.3/clear.so \
    -executable=appdir/usr/lib/x86_64-linux-gnu/gegl-0.3/fractal-trace.so \
    -executable=appdir/usr/lib/x86_64-linux-gnu/gegl-0.3/gegl-buffer-save-op.so \
    -executable=appdir/usr/lib/x86_64-linux-gnu/gegl-0.3/nop.so \
    -executable=appdir/usr/lib/x86_64-linux-gnu/gegl-0.3/save.so \
    -executable=appdir/usr/lib/x86_64-linux-gnu/gegl-0.3/motion-blur-linear.so \
    -executable=appdir/usr/lib/x86_64-linux-gnu/gegl-0.3/cartoon.so \
    -executable=appdir/usr/lib/x86_64-linux-gnu/gegl-0.3/matting-levin.so \
    -executable=appdir/usr/lib/x86_64-linux-gnu/gegl-0.3/noise-hurl.so \
    -executable=appdir/usr/lib/x86_64-linux-gnu/gegl-0.3/panorama-projection.so \
    -executable=appdir/usr/lib/x86_64-linux-gnu/gegl-0.3/noise-perlin.so \
    -executable=appdir/usr/lib/x86_64-linux-gnu/gegl-0.3/write-buffer.so \
    -executable=appdir/usr/lib/x86_64-linux-gnu/gegl-0.3/copy-buffer.so \
    -executable=appdir/usr/lib/x86_64-linux-gnu/gegl-0.3/noise-pick.so \
    -executable=appdir/usr/lib/x86_64-linux-gnu/gegl-0.3/softglow.so \
    -executable=appdir/usr/lib/x86_64-linux-gnu/gegl-0.3/invert-linear.so \
    -executable=appdir/usr/lib/x86_64-linux-gnu/gegl-0.3/vector-fill.so \
    -executable=appdir/usr/lib/x86_64-linux-gnu/gegl-0.3/polar-coordinates.so \
    -executable=appdir/usr/lib/x86_64-linux-gnu/gegl-0.3/src-atop.so \
    -executable=appdir/usr/lib/x86_64-linux-gnu/gegl-0.3/dropshadow.so \
    -executable=appdir/usr/lib/x86_64-linux-gnu/gegl-0.3/color-temperature.so \
    -executable=appdir/usr/lib/x86_64-linux-gnu/gegl-0.3/contrast-curve.so \
    -executable=appdir/usr/lib/x86_64-linux-gnu/gegl-0.3/red-eye-removal.so \
    -executable=appdir/usr/lib/x86_64-linux-gnu/gegl-0.3/jp2-load.so \
    -executable=appdir/usr/lib/x86_64-linux-gnu/gegl-0.3/color-burn.so \
    -executable=appdir/usr/lib/x86_64-linux-gnu/gegl-0.3/edge-sobel.so \
    -executable=appdir/usr/lib/x86_64-linux-gnu/gegl-0.3/overlay.so \
    -executable=appdir/usr/lib/x86_64-linux-gnu/gegl-0.3/exp-combine.so \
    -executable=appdir/usr/lib/x86_64-linux-gnu/gegl-0.3/color-rotate.so \
    -executable=appdir/usr/lib/x86_64-linux-gnu/gegl-0.3/brightness-contrast.so \
    -executable=appdir/usr/lib/x86_64-linux-gnu/gegl-0.3/edge.so \
    -executable=appdir/usr/lib/x86_64-linux-gnu/gegl-0.3/crop.so \
    -executable=appdir/usr/lib/x86_64-linux-gnu/gegl-0.3/exposure.so \
    -executable=appdir/usr/lib/x86_64-linux-gnu/gegl-0.3/npy-save.so \
    -executable=appdir/usr/lib/x86_64-linux-gnu/gegl-0.3/color.so \
    -executable=appdir/usr/lib/x86_64-linux-gnu/gegl-0.3/image-compare.so \
    -executable=appdir/usr/lib/x86_64-linux-gnu/gegl-0.3/displace.so \
    -executable=appdir/usr/lib/x86_64-linux-gnu/gegl-0.3/gaussian-blur.so \
    -executable=appdir/usr/lib/x86_64-linux-gnu/gegl-0.3/dst-out.so \
    -executable=appdir/usr/lib/x86_64-linux-gnu/gegl-0.3/noise-rgb.so \
    -executable=appdir/usr/lib/x86_64-linux-gnu/gegl-0.3/stretch-contrast-hsv.so \
    -executable=appdir/usr/lib/x86_64-linux-gnu/gegl-0.3/lcms-from-profile.so \
    -executable=appdir/usr/lib/x86_64-linux-gnu/gegl-0.3/src-out.so \
    -executable=appdir/usr/lib/x86_64-linux-gnu/gegl-0.3/cache.so \
    -executable=appdir/usr/lib/x86_64-linux-gnu/gegl-0.3/lens-distortion.so \
    -executable=appdir/usr/lib/x86_64-linux-gnu/gegl-0.3/motion-blur-zoom.so \
    -executable=appdir/usr/lib/x86_64-linux-gnu/gegl-0.3/motion-blur-circular.so \
    -executable=appdir/usr/lib/x86_64-linux-gnu/gegl-0.3/difference.so \
    -executable=appdir/usr/lib/x86_64-linux-gnu/gegl-0.3/src.so \
    -executable=appdir/usr/lib/x86_64-linux-gnu/gegl-0.3/svg-load.so \
    -executable=appdir/usr/lib/x86_64-linux-gnu/gegl-0.3/darken.so \
    -executable=appdir/usr/lib/x86_64-linux-gnu/gegl-0.3/grey.so \
    -executable=appdir/usr/lib/x86_64-linux-gnu/gegl-0.3/remap.so \
    -executable=appdir/usr/lib/x86_64-linux-gnu/gegl-0.3/wind.so \
    -executable=appdir/usr/lib/x86_64-linux-gnu/gegl-0.3/divide.so \
    -executable=appdir/usr/lib/x86_64-linux-gnu/gegl-0.3/deinterlace.so \
    -executable=appdir/usr/lib/x86_64-linux-gnu/gegl-0.3/tile.so \
    -executable=appdir/usr/lib/x86_64-linux-gnu/gegl-0.3/save-pixbuf.so \
    -executable=appdir/usr/lib/x86_64-linux-gnu/gegl-0.3/bump-map.so \
    -executable=appdir/usr/lib/x86_64-linux-gnu/gegl-0.3/color-dodge.so \
    -executable=appdir/usr/lib/x86_64-linux-gnu/gegl-0.3/cubism.so \
    -executable=appdir/usr/lib/x86_64-linux-gnu/gegl-0.3/layer.so \
    -executable=appdir/usr/lib/x86_64-linux-gnu/gegl-0.3/alien-map.so \
    -executable=appdir/usr/lib/x86_64-linux-gnu/gegl-0.3/tile-paper.so \
    -executable=appdir/usr/lib/x86_64-linux-gnu/gegl-0.3/engrave.so \
    -executable=appdir/usr/lib/x86_64-linux-gnu/gegl-0.3/fractal-explorer.so \
    -executable=appdir/usr/lib/x86_64-linux-gnu/gegl-0.3/noise-cie-lch.so \
    -executable=appdir/usr/lib/x86_64-linux-gnu/gegl-0.3/svg-matrix.so \
    -executable=appdir/usr/lib/x86_64-linux-gnu/gegl-0.3/src-in.so \
    -executable=appdir/usr/lib/x86_64-linux-gnu/gegl-0.3/over.so \
    -executable=appdir/usr/lib/x86_64-linux-gnu/gegl-0.3/color-to-alpha.so \
    -executable=appdir/usr/lib/x86_64-linux-gnu/gegl-0.3/dst-atop.so \
    -executable=appdir/usr/lib/x86_64-linux-gnu/gegl-0.3/clone.so \
    -executable=appdir/usr/lib/x86_64-linux-gnu/gegl-0.3/seamless-clone-compose.so \
    -executable=appdir/usr/lib/x86_64-linux-gnu/gegl-0.3/sdl-display.so \
    -executable=appdir/usr/lib/x86_64-linux-gnu/gegl-0.3/ppm-save.so \
    -executable=appdir/usr/lib/x86_64-linux-gnu/gegl-0.3/value-invert.so \
    -executable=appdir/usr/lib/x86_64-linux-gnu/gegl-0.3/box-blur.so \
    -executable=appdir/usr/lib/x86_64-linux-gnu/gegl-0.3/pixbuf.so \
    -executable=appdir/usr/lib/x86_64-linux-gnu/gegl-0.3/fattal02.so \
    -executable=appdir/usr/lib/x86_64-linux-gnu/gegl-0.3/edge-laplace.so \
    -executable=appdir/usr/lib/x86_64-linux-gnu/gegl-0.3/png-load.so \
    -executable=appdir/usr/lib/x86_64-linux-gnu/gegl-0.3/svg-multiply.so \
    -executable=appdir/usr/lib/x86_64-linux-gnu/gegl-0.3/value-propagate.so \
    -executable=appdir/usr/lib/x86_64-linux-gnu/gegl-0.3/svg-luminancetoalpha.so \
    -executable=appdir/usr/lib/x86_64-linux-gnu/gegl-0.3/mono-mixer.so \
    -executable=appdir/usr/lib/x86_64-linux-gnu/gegl-0.3/dcraw-load.so \
    -executable=appdir/usr/lib/x86_64-linux-gnu/gegl-0.3/illusion.so \
    -executable=appdir/usr/lib/x86_64-linux-gnu/gegl-0.3/noise-reduction.so \
    -executable=appdir/usr/lib/x86_64-linux-gnu/gegl-0.3/bilateral-filter.so \
    -executable=appdir/usr/lib/x86_64-linux-gnu/gegl-0.3/sepia.so \
    -executable=appdir/usr/lib/x86_64-linux-gnu/gegl-0.3/exclusion.so \
    -executable=appdir/usr/lib/x86_64-linux-gnu/gegl-0.3/jpg-load.so \
    -executable=appdir/usr/lib/x86_64-linux-gnu/gegl-0.3/ripple.so \
    -executable=appdir/usr/lib/x86_64-linux-gnu/gegl-0.3/snn-mean.so \
    -executable=appdir/usr/lib/x86_64-linux-gnu/gegl-0.3/mantiuk06.so \
    -executable=appdir/usr/lib/x86_64-linux-gnu/gegl-0.3/difference-of-gaussians.so \
    -executable=appdir/usr/lib/x86_64-linux-gnu/gegl-0.3/jpg-save.so \
    -executable=appdir/usr/lib/x86_64-linux-gnu/gegl-0.3/dst.so \
    -executable=appdir/usr/lib/x86_64-linux-gnu/gegl-0.3/linear-gradient.so \
    -executable=appdir/usr/lib/x86_64-linux-gnu/gegl-0.3/subtract.so \
    -executable=appdir/usr/lib/x86_64-linux-gnu/gegl-0.3/screen.so \
    -executable=appdir/usr/lib/x86_64-linux-gnu/gegl-0.3/transformops.so \
    -executable=appdir/usr/lib/x86_64-linux-gnu/gegl-0.3/noise-hsv.so \
    -executable=appdir/usr/lib/x86_64-linux-gnu/gegl-0.3/c2g.so \
    -executable=appdir/usr/lib/x86_64-linux-gnu/gegl-0.3/noise-slur.so \
    -executable=appdir/usr/lib/x86_64-linux-gnu/gegl-0.3/json.so \
    -executable=appdir/usr/lib/x86_64-linux-gnu/gegl-0.3/dst-in.so \
    -executable=appdir/usr/lib/x86_64-linux-gnu/gegl-0.3/noise-cell.so \
    -executable=appdir/usr/lib/x86_64-linux-gnu/gegl-0.3/xor.so \
    -executable=appdir/usr/lib/x86_64-linux-gnu/gegl-0.3/radial-gradient.so \
    -executable=appdir/usr/lib/x86_64-linux-gnu/gegl-0.3/bilateral-filter-fast.so \
    -executable=appdir/usr/lib/x86_64-linux-gnu/gegl-0.3/photocopy.so \
    -executable=appdir/usr/lib/x86_64-linux-gnu/gegl-0.3/levels.so \
    -executable=appdir/usr/lib/x86_64-linux-gnu/gegl-0.3/weighted-blend.so \
    -executable=appdir/usr/lib/x86_64-linux-gnu/gegl-0.3/waves.so \
    -executable=appdir/usr/lib/x86_64-linux-gnu/gegl-0.3/stress.so \
    -executable=appdir/usr/lib/x86_64-linux-gnu/gegl-0.3/introspect.so \
    -executable=appdir/usr/lib/x86_64-linux-gnu/gegl-0.3/svg-saturate.so \
    -executable=appdir/usr/lib/x86_64-linux-gnu/gegl-0.3/oilify.so \
    -executable=appdir/usr/lib/x86_64-linux-gnu/gegl-0.3/apply-lens.so \
    -executable=appdir/usr/lib/x86_64-linux-gnu/gegl-0.3/mirrors.so \
    -executable=appdir/usr/lib/x86_64-linux-gnu/gegl-0.3/mosaic.so \
    -executable=appdir/usr/lib/x86_64-linux-gnu/gegl-0.3/noise-spread.so \
    -executable=appdir/usr/lib/x86_64-linux-gnu/gegl-0.3/path.so \
    -executable=appdir/usr/lib/x86_64-linux-gnu/gegl-0.3/tile-glass.so \
    -executable=appdir/usr/lib/x86_64-linux-gnu/gegl-0.3/invert-gamma.so \
    -executable=appdir/usr/lib/x86_64-linux-gnu/gegl-0.3/high-pass.so \
    -executable=appdir/usr/lib/x86_64-linux-gnu/gegl-0.3/supernova.so \
    -executable=appdir/usr/lib/x86_64-linux-gnu/gegl-0.3/antialias.so \
    -executable=appdir/usr/lib/x86_64-linux-gnu/gegl-0.3/gaussian-blur-iir.so \
    -executable=appdir/usr/lib/x86_64-linux-gnu/gegl-0.3/pixelize.so \
    -executable=appdir/usr/lib/x86_64-linux-gnu/gegl-0.3/seamless-clone.so \
    -executable=appdir/usr/lib/x86_64-linux-gnu/gegl-0.3/reinhard05.so \
    -executable=appdir/usr/lib/x86_64-linux-gnu/gegl-0.3/whirl-pinch.so \
    -executable=appdir/usr/lib/x86_64-linux-gnu/gegl-0.3/noise-solid.so \
    -executable=appdir/usr/lib/x86_64-linux-gnu/gegl-0.3/magick-load.so \
    -executable=appdir/usr/lib/x86_64-linux-gnu/gegl-0.3/shift.so \
    -executable=appdir/usr/lib/x86_64-linux-gnu/gegl-0.3/lens-flare.so \
    -executable=appdir/usr/lib/x86_64-linux-gnu/gegl-0.3/gblur-1d.so \
    -executable=appdir/usr/lib/x86_64-linux-gnu/gegl-0.3/opacity.so \
    -executable=appdir/usr/lib/x86_64-linux-gnu/gegl-0.3/rectangle.so \
    -executable=appdir/usr/lib/x86_64-linux-gnu/gegl-0.3/gegl-buffer-load-op.so

after_success:
  - wget -c https://github.com/probonopd/uploadtool/raw/master/upload.sh
  - bash upload.sh Laidout*.AppImage*
  
branches:
  only:
    - master
    - release
  #except:
  #  - # Do not build tags that we create when we upload to GitHub Releases
  #  - /^(?i:continuous)/
